[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'
NIXPACKS_PATH = '/usr/local/bin:/usr/bin:/bin'

[phases.setup]
nixPkgs = [
  'nodejs_23',
  'bun',
]
